Implement Python 3.12 compatible loader. Fixes #130.
thp/pyotherside pull request #131
Opened 2024-03-11 12:16 UTC by apollo13

2024-03-12 03:55 UTC, thp requested changes
Thanks! Some comments inline plus these:

- Add a changelog entry in `Version UNRELEASED` section in `docs/index.rst` for this
- In `.github/workflows/build.yaml`, change `python@3.8` to `python@3.12`
- As some of these loader features were only introduced in a Python version >= 3.3, we should bump the minimum version in `README.md` to Python 3.8, as everything before that [is end-of-life](https://devguide.python.org/versions/) (+ add to the changelog)

2024-03-12 03:55 UTC, thp commented on src/qrc_importer.py
> +        return
Make it more explicit that this returns `None` as per [the docs](https://docs.python.org/3/library/importlib.html#importlib.abc.Loader.create_module):

```suggestion
        return None
```

2024-03-12 03:55 UTC, thp commented on src/qrc_importer.py
> +        return
Also here, `python3 -m this | grep Explicit`:

```suggestion
        return None
```

2024-04-17 13:27 UTC, apollo13 commented
@thp Is there anything you miss here?

2024-04-24 18:04 UTC, thp approved these changes
Nice, thanks!

2024-04-24 18:04 UTC, merged

2024-05-10 11:21 UTC, uaqben commented
@thp you plan to tag a release including this fix?  fixes [yubikey-manager-qt](https://github.com/Yubico/yubikey-manager-qt/issues/357)

2024-05-18 21:11 UTC, thp commented
> @thp you plan to tag a release including this fix? fixes [yubikey-manager-qt](https://github.com/Yubico/yubikey-manager-qt/issues/357) 😊

PyOtherSide 1.6.1 is now released.